language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - pypy

install:
    - python setup.py install

script:
    - make test
    - source env/bin/activate && pip install --quiet coverage && coverage run --omit='*/site-packages/*,*/distutils/*' ./test/test.py
    - source env/bin/activate && coverage report --show-missing

after_success:
    - pip install --quiet coveralls
    - coveralls
